# Generated by Django 3.0 on 2019-12-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='soem dexcsd'),
            preserve_default=False,
        ),
    ]
